# Generated by Django 4.1.5 on 2023-01-30 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assetsData', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift_History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('From_Location', models.CharField(max_length=200)),
                ('To_Location', models.CharField(max_length=200)),
                ('Date', models.DateField()),
                ('remarks', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ledger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_No', models.CharField(max_length=500)),
                ('Date_Of_Entry', models.DateField()),
                ('Date_Of_Invoice', models.DateField()),
                ('Quantity', models.IntegerField()),
                ('Rate', models.CharField(max_length=200)),
                ('Discount', models.CharField(max_length=100)),
                ('Tax', models.CharField(max_length=100)),
                ('Ammount', models.CharField(max_length=1000)),
                ('make', models.CharField(max_length=500)),
                ('Make_No', models.CharField(max_length=200)),
                ('Location_Code', models.CharField(blank=True, max_length=200, null=True)),
                ('Item_Code', models.CharField(max_length=200)),
                ('Final_Code', models.CharField(blank=True, max_length=500, null=True)),
                ('remark', models.TextField(blank=True, null=True)),
                ('Is_Dump', models.BooleanField(default=False)),
                ('Finantial_Year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assetsData.finantial_year')),
                ('Main_Catagory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assetsData.main_catagory')),
                ('Purchase_Item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assetsData.asset_type')),
                ('Shift_History', models.ManyToManyField(to='store.shift_history')),
                ('Sub_Catagory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assetsData.sub_catagory')),
                ('Vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assetsData.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='Dump',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dump_Date', models.DateField()),
                ('Remark', models.TextField(blank=True, null=True)),
                ('Is_Sold', models.BooleanField(default=False)),
                ('Date_Of_Sold', models.DateField(blank=True, null=True)),
                ('Sold_Price', models.CharField(blank=True, max_length=100, null=True)),
                ('Item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.ledger')),
            ],
        ),
    ]
