# Generated by Django 4.1.5 on 2023-02-09 10:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ledger',
            name='Main_Catagory',
        ),
        migrations.RemoveField(
            model_name='ledger',
            name='Make_No',
        ),
        migrations.RemoveField(
            model_name='ledger',
            name='Sub_Catagory',
        ),
        migrations.AddField(
            model_name='ledger',
            name='assigned_to',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shift_history',
            name='from_User',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shift_from_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shift_history',
            name='to_User',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shift_to_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ledger',
            name='make',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='shift_history',
            name='Date',
            field=models.DateField(auto_now=True),
        ),
        migrations.CreateModel(
            name='assign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickedUp', models.BooleanField(default=False)),
                ('assigned_to_pickup', models.CharField(max_length=100)),
                ('assigned_person', models.BooleanField(default=False)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.ledger')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
