# Generated by Django 4.1.5 on 2023-02-09 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assetsData', '0005_stock_register_departments_code'),
        ('store', '0002_remove_ledger_main_catagory_remove_ledger_make_no_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ledger',
            name='Quantity',
        ),
        migrations.RemoveField(
            model_name='ledger',
            name='assigned_to',
        ),
        migrations.AddField(
            model_name='ledger',
            name='buy_for',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assetsData.departments'),
        ),
        migrations.AddField(
            model_name='ledger',
            name='stock_register',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assetsData.stock_register'),
        ),
    ]
