# Generated by Django 4.1.5 on 2023-02-09 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_remove_ledger_quantity_remove_ledger_assigned_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledger',
            name='sno',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
