# Generated by Django 4.1.5 on 2023-02-09 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_ledger_sno'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledger',
            name='isIssued',
            field=models.BooleanField(default=False),
        ),
    ]
