# Generated by Django 4.1.5 on 2023-02-09 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_ledger_isissued'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledger',
            name='Shift_History',
            field=models.ManyToManyField(null=True, to='store.shift_history'),
        ),
    ]
