# Generated by Django 4.1.5 on 2023-10-25 13:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0005_remove_shift_history_from_location_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ledger",
            options={"ordering": ["Purchase_Item__name"]},
        ),
        migrations.AddField(
            model_name="assign",
            name="dumped_review",
            field=models.BooleanField(default=False),
        ),
    ]
