# Generated by Django 4.1.5 on 2023-10-28 00:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0006_alter_ledger_options_assign_dumped_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="ledger",
            name="item_type",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
