# Generated by Django 4.1.5 on 2023-02-09 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_ledger_shift_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledger',
            name='Shift_History',
            field=models.ManyToManyField(blank=True, to='store.shift_history'),
        ),
    ]
