# Generated by Django 4.1.5 on 2023-10-28 00:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0007_ledger_item_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="assign",
            name="dump_remark",
            field=models.TextField(blank=True, null=True),
        ),
    ]
