# Generated by Django 4.1.5 on 2023-02-09 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assetsData', '0006_profile'),
        ('store', '0007_alter_ledger_shift_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assign',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='assetsData.profile'),
        ),
    ]
