# Generated by Django 4.1.5 on 2023-03-20 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("assetsData", "0010_backupdate_backup_user_backupdate_user_ip_complaints"),
        ("store", "0008_alter_assign_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assign",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="assetsData.profile"
            ),
        ),
    ]
