# Generated by Django 4.1.5 on 2023-10-28 00:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0008_assign_dump_remark"),
    ]

    operations = [
        migrations.AddField(
            model_name="assign",
            name="action_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
