# Generated by Django 4.1.5 on 2023-10-28 13:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("assetsData", "0004_profile_login_type"),
        ("store", "0009_assign_action_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assign",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="store.ledger"
            ),
        ),
        migrations.AlterField(
            model_name="assign",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="ledger",
            name="Financial_Year",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="assetsData.finantial_year",
            ),
        ),
        migrations.AlterField(
            model_name="ledger",
            name="Location_Code",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="assetsData.location_description",
            ),
        ),
        migrations.AlterField(
            model_name="ledger",
            name="Purchase_Item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="assetsData.asset_type",
            ),
        ),
        migrations.AlterField(
            model_name="ledger",
            name="buy_for",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="assetsData.departments",
            ),
        ),
        migrations.AlterField(
            model_name="ledger",
            name="current_department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="new_department",
                to="assetsData.departments",
            ),
        ),
        migrations.AlterField(
            model_name="ledger",
            name="stock_register",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="assetsData.stock_register",
            ),
        ),
        migrations.CreateModel(
            name="entry_to_register",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pageno", models.IntegerField()),
                (
                    "register_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "finantial_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="assetsData.finantial_year",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="store.ledger",
                    ),
                ),
            ],
        ),
    ]
