# Generated by Django 4.1.5 on 2023-10-28 14:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0010_alter_assign_item_alter_assign_user_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="entry_to_register",
            old_name="finantial_year",
            new_name="finantialYear",
        ),
    ]
