# Generated by Django 4.2.7 on 2023-11-28 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_rename_finantial_year_entry_to_register_finantialyear'),
    ]

    operations = [
        migrations.CreateModel(
            name='admin_notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_date', models.DateTimeField()),
                ('notification', models.TextField()),
                ('status', models.CharField(default='unread', max_length=100)),
                ('notification_type', models.CharField(max_length=100)),
            ],
        ),
    ]
