# Generated by Django 4.2.7 on 2023-12-01 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_admin_notifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry_to_register',
            name='pageno',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
