# Generated by Django 4.2.7 on 2023-12-01 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_alter_entry_to_register_pageno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry_to_register',
            name='finantialYear',
        ),
        migrations.RemoveField(
            model_name='entry_to_register',
            name='item',
        ),
        migrations.RemoveField(
            model_name='entry_to_register',
            name='pageno',
        ),
    ]
