# Generated by Django 4.2.7 on 2023-12-01 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assetsData', '0004_profile_login_type'),
        ('store', '0014_remove_entry_to_register_finantialyear_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry_to_register',
            name='finantialYear',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='assetsData.finantial_year'),
        ),
        migrations.AddField(
            model_name='entry_to_register',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='store.ledger'),
        ),
        migrations.AddField(
            model_name='entry_to_register',
            name='pageno',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
