# Generated by Django 4.1.5 on 2023-12-04 06:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("store", "0015_entry_to_register_finantialyear_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="entry_to_register",
            options={"ordering": ["-id"]},
        ),
        migrations.CreateModel(
            name="employee_notifications",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("notification_date", models.DateTimeField()),
                ("notification", models.TextField()),
                ("status", models.CharField(default="unread", max_length=100)),
                ("notification_type", models.CharField(max_length=100)),
                ("action_url", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
