# Generated by Django 4.1.5 on 2023-12-06 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("assetsData", "0005_remove_main_catagory_consumable_type"),
        ("store", "0016_alter_entry_to_register_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entry_to_register",
            name="item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="assetsData.asset_type",
            ),
        ),
    ]
