# Generated by Django 4.1.5 on 2023-12-08 10:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0017_alter_entry_to_register_item"),
    ]

    operations = [
        migrations.AddField(
            model_name="ledger",
            name="pono",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
