# Generated by Django 4.1.5 on 2023-12-15 13:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0018_ledger_pono"),
    ]

    operations = [
        migrations.CreateModel(
            name="grn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("poid", models.CharField(max_length=100)),
            ],
        ),
    ]
