# Generated by Django 4.1.5 on 2023-01-31 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetsData', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='Email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
