# Generated by Django 4.1.5 on 2023-01-31 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetsData', '0002_vendor_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='attach',
            field=models.ManyToManyField(blank=True, to='assetsData.vendor_attachments'),
        ),
    ]
