# Generated by Django 4.1.5 on 2023-01-31 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assetsData', '0003_vendor_attach'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset_type',
            name='mc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='assetsData.main_catagory'),
        ),
        migrations.AddField(
            model_name='asset_type',
            name='sc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='assetsData.sub_catagory'),
        ),
    ]
