# Generated by Django 4.1.5 on 2023-02-09 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetsData', '0004_asset_type_mc_asset_type_sc'),
    ]

    operations = [
        migrations.CreateModel(
            name='stock_register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='departments',
            name='code',
            field=models.CharField(default=' ', max_length=100),
        ),
    ]
