# Generated by Django 4.1.5 on 2023-12-06 15:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assetsData", "0005_remove_main_catagory_consumable_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asset_type",
            name="Final_Code",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
