# Generated by Django 4.1.5 on 2023-03-12 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assetsData', '0006_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='location_description',
            name='building',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assetsData.building_name'),
        ),
    ]
