# Generated by Django 4.1.5 on 2023-03-12 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assetsData', '0007_location_description_building'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location_description',
            old_name='name',
            new_name='description',
        ),
    ]
