# Generated by Django 4.1.5 on 2023-03-12 19:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assetsData", "0008_rename_name_location_description_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="backupDate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now=True)),
            ],
        ),
    ]
